apiVersion: apps/v1
kind: Deployment
metadata:
  name: webservice-devops-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devops
  template:
    metadata:
      labels:
        app: devops
    spec:
      containers:
      - name: webservice-devops-container
        image: yanisboumrah/webservicedevops:latest
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: webservice-devops-service
spec:
  selector:
    app: devops
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
